"""empty message

Revision ID: ae793e18a422
Revises: b032e38486f5
Create Date: 2021-10-17 00:22:33.406823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae793e18a422'
down_revision = 'b032e38486f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_like_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('play_id', sa.Integer(), nullable=False),
    sa.Column('fan_id', sa.Integer(), nullable=False),
    sa.Column('like_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fan_id'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['play_id'], ['play_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('play_id', 'fan_id')
    )
    op.alter_column('play_table', 'sms_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='推送的sms数量',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('play_table', 'sms_count',
               existing_type=sa.INTEGER(),
               comment='推送的sms数量',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_table('post_like_table')
    # ### end Alembic commands ###
