"""empty message

Revision ID: b032e38486f5
Revises: a1854734a245
Create Date: 2021-04-29 00:48:37.922763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b032e38486f5'
down_revision = 'a1854734a245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tier_table', sa.Column('price_id', sa.Text(), nullable=True))
    op.add_column('tier_table', sa.Column('product_id', sa.Text(), nullable=True))
    op.add_column('user_table', sa.Column('customer_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'customer_id')
    op.drop_column('tier_table', 'product_id')
    op.drop_column('tier_table', 'price_id')
    # ### end Alembic commands ###
